--ce fichier est le script MLD du projet integrateur du groupe 6--
ORGANISATIONS (id_Organisation(PK), nom, adresse, telephone, statut, nbr_entrepôt, date_creation, date_maj)
INDIVIDUS (id_Individu(PK), nom, prenom, adresse, adresse, telephone, email, password, statut)
Repertoire ((id_Organisation, id_Individu)(PK), id_organisation(FK), id_individus(FK))
PRODUITS (id_Produit(PK), nom, description, marque, modèle, fournisseur, date_fabrique, date_peremption)
RECEPTIONS (id_Reception(PK), date_reception, statut)
EXPEDITIONS (id_Expedition(PK), date_expedition)
LOT (id_Lot(PK), id_Produit(FK), fournisseur, date_reception, date_expedition, quantite, description)
MATERIELS_EMBALLAGES (id_MatEmballage(FK), type_emballage, etat_emballage)
CELLULES (id_Cellule(PK), longeur, largeur, hauteur, masse_Maximale)
ZONE_STOCKAGE (id_ZoStock, id_Entrepôt(FK), id_Cellule(FK), E1, E2, E3)
COLIS (idColis(PK), id_MatEmballage(FK), id_reception(FK), dimension, poids, emplacement)
CONTENUS_COLIS (id_ConColis(PK), id_Colis(FK), quantite_produits)
ENTREPOTS (identrepôt(PK), idOrganisation(FK), nom_organisation, capacite, stockage, emplacement)
BON_RECEPTIONS (id_Bon_reception(PK), id_Reception(FK), id_Magasinier(FK), id_Commande(FK), date_reception, observation, fournisseur, Liste_article_reçus, reference_commande)
BON_EXPEDITIONS (id_Bon_expedition(PK), id_Client(FK), id_Colis(FK), client, reference_commande, date_livraison, observation, liste_articles_livres, transporteurs)
MAGASINIERS (id_Magasinier(PK), idindividu(FK))
RAPPORTS_EXCEPTIONS (id_Rapport(PK), id_Bon_reception(FK), id_Produit(FK), id_Individu(FK), date, type_exception, processus_concerne, produit_concerne, observation, detecteur, action_entreprise)
COMMANDES_ACHATS (id_Commande(PK) (FK), idCommande, date_commande, statut, quantite)
COMMANDES_VENDS (id_Commande(PK) (FK), #idCommande, #idClient, date_commande, statut, quantite)
COMMANDES (idCommande(PK), quantite, prixUnitaire)
